"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$conda\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "bold peach"
format = '[$symbol]($style) '

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bold peach"
style_root = "bold red"
format = '[$user]($style) [›](overlay1) '

[directory]
style = "bold lavender"
format = "[ $path]($style) [›](overlay1) "
truncation_length = 4
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bold mauve"
format = '[$symbol $branch]($style) '

[git_status]
style = "bold mauve"
format = '[$all_status$ahead_behind ]($style)[›](overlay1) '

[nodejs]
symbol = ""
style = "bold green"
format = '[$symbol($version)]($style) [›](overlay1) '

[c]
symbol = " "
style = "bold blue"
format = '[$symbol($version)]($style) [›](overlay1) '

[rust]
symbol = ""
style = "bold peach"
format = '[$symbol($version)]($style) [›](overlay1) '

[golang]
symbol = ""
style = "bold sapphire"
format = '[$symbol($version)]($style) [›](overlay1) '

[php]
symbol = ""
style = "bold lavender"
format = '[$symbol($version)]($style) [›](overlay1) '

[java]
symbol = ""
style = "bold red"
format = '[$symbol($version)]($style) [›](overlay1) '

[kotlin]
symbol = ""
style = "bold mauve"
format = '[$symbol($version)]($style) [›](overlay1) '

[haskell]
symbol = ""
style = "bold mauve"
format = '[$symbol($version)]($style) [›](overlay1) '

[python]
symbol = ""
style = "bold yellow"
format = '[$symbol($version)]($style) [›](overlay1) '

[docker_context]
symbol = ""
style = "bold blue"
format = '[$symbol($context)]($style) [›](overlay1) '

[conda]
style = "bold green"
format = '[$symbol($environment)]($style) [›](overlay1) '

[time]
disabled = false
time_format = "%R"
style = "subtext0"
format = '[ $time]($style) '

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[[󰄛](green) ❯](peach)'
error_symbol = '[[󰄛](red) ❯](peach)'
vimcmd_symbol = '[󰄛 ❮](subtext1)'
vimcmd_replace_one_symbol = '[󰄛 ❮](mauve)'
vimcmd_replace_symbol = '[󰄛 ❮](mauve)'
vimcmd_visual_symbol = '[󰄛 ❮](yellow)'
