profiles:
  zettle-stage:
    name: "PowerUser-120569643495"
    description: "Zettle Stage Account"
    account_id: "120569643495"
    role: "PowerUser"
  
  # Add more profiles here as needed
  # Example:
  # prod:
  #   name: "production-profile-name"
  #   description: "Production Environment"
  #   account_id: "123456789012"
  #   role: "ReadOnly"