[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
normal = { family = "FantasqueSansM Nerd Font Mono", style = "Regular" }
size = 20

[window]
startup_mode = "Maximized"
decorations = "buttonless"
dynamic_padding = false

[window.padding]
y = 20
