[env]
AWS_PROFILE = "PowerUser-120569643495"
CURL_SSL_BACKEND = "secure-transport"
NODE_EXTRA_CA_CERTS = "/usr/local/etc/openssl/certs/paypal_proxy_cacerts.pem"

[tools]
neovim = "latest"
node = "latest"
rust = "latest"

[tasks.setup]
description = "First-time setup for a new machine"
run = """
cp -v ./fonts/* ~/Library/Fonts
"""

[tasks.stow]
description = "Stow the dotfiles"
run = "stow -t ~/ stow"
